[general]

import = ["~/.config/alacritty/dracula.toml"]

[font]

size = 12.0

[font.normal]

family = "UDEV Gothic"
style = "Regular"

[font.bold]

family = "UDEV Gothic"
style = "Bold"

[font.italic]

family = "UDEV Gothic"
style = "Italic"

[font.bold_italic]

family = "UDEV Gothic"
style = "Bold Italic"
